### ISSUE TITLE
possible issue with ah_token

### ISSUE THREAD

**Issue by djdanielsson** [redhat-cop/ah_configuration#109]
I might need to do some more in depth testing but it appears that ah_token doesn't work when run in controller. I am able to run my playbook just fine on CLI but when I tried running on controller it fails. I will try and get some error logs soon and add them to this issue.

**Comment by sean-m-sullivan** [comment]
@djdanielsson can you retest this, I've seen some issues with tokens and user/passwords being mixed and it resets the token, but we have all these tests, so lets figure this one out.

**Comment by djdanielsson** [comment]
I won't be able to get to it for quite a while.... I wish I remembered what I was doing that saw the issue... but it should be pretty easy to test, generate a token then try and use user/pass for everything possible and see if the token works or not. I just won't be able to try this myself for a month probably

**Comment by djdanielsson** [comment]
Actually we might want to automate it and create it as a test to ensure this type of issue doesn't happen again since we currently maintain the modules which is where the issue resides

**Comment by djdanielsson** [comment]
I think I am just going to close this for now and if I start to see it again I will re-open
