### ISSUE TITLE
Update ah_repository_sync to just run against community and rh_certified

### ISSUE THREAD

**Issue by Tompage1994** [redhat-cop/ah_configuration#126]
We want to replicate the changes made in ah_repository in #124

> also another thought I had, should I make the sync role mirror this new layout? and if so, what are your thoughts on making an option so it could call the sync from this role as well? @Tompage1994 @sean-m-sullivan

The sync role could definitely follow this track. I suppose it can't hurt to call the sync role from this role too if a `.sync` option is provided. I'd suggest all this to be a separate PR and separate issue

_Originally posted by @Tompage1994 in https://github.com/redhat-cop/ah_configuration/issues/124#issuecomment-1178730152_

**Comment by sean-m-sullivan** [comment]
I thought it would be better to implement it inside the module that ah_repository uses similar to how awx.project can sync and wait, that way it can be done in one step in both, instead of just the role.

**Comment by Tompage1994** [comment]
Resolved by #152
