### ISSUE TITLE
redhat_cop.ah_configuration.ah_approval fails with error like [error] Bash exited with code 2

### ISSUE THREAD

**Issue by gabhishek627** [redhat-cop/ah_configuration#127]
- redhat_cop.ah_configuration (v 0.8.0)
- The task for redhat_cop.ah_configuration.ah_collection works fine
- while approving the collection ( via redhat_cop.ah_configuration.ah_approval) it fails with error like [error] Bash exited with code 2
-  The failure with the approval appears randomly for any collection

- Approve collections with retries to 10
TASK [Approve Collections] *****************************************************
FAILED - RETRYING: [localhost]: Approve Collections (10 retries left).
FAILED - RETRYING: [localhost]: Approve Collections (9 retries left).
FAILED - RETRYING: [localhost]: Approve Collections (8 retries left).
FAILED - RETRYING: [localhost]: Approve Collections (7 retries left).
FAILED - RETRYING: [localhost]: Approve Collections (6 retries left).
FAILED - RETRYING: [localhost]: Approve Collections (5 retries left).
FAILED - RETRYING: [localhost]: Approve Collections (4 retries left).
FAILED - RETRYING: [localhost]: Approve Collections (3 retries left).
FAILED - RETRYING: [localhost]: Approve Collections (2 retries left).
FAILED - RETRYING: [localhost]: Approve Collections (1 retries left).

**Comment by Tompage1994** [comment]
Could you show what the error looks like after all the retries have failed? Could you run your play with `-vvv` and provide the full output for this task please?

**Comment by Tompage1994** [comment]
Could you also ensure there is a collection awaiting approval in the UI?

**Comment by gabhishek627** [comment]
No, Whenever it fails the approval never appears, the failed ones are still unavailable in the approval screen.

**Comment by gabhishek627** [comment]
TASK [Approve Collections] *****************************************************
FAILED - RETRYING: [localhost]: Approve Collections (10 retries left).
FAILED - RETRYING: [localhost]: Approve Collections (9 retries left).
FAILED - RETRYING: [localhost]: Approve Collections (8 retries left).
FAILED - RETRYING: [localhost]: Approve Collections (7 retries left).
FAILED - RETRYING: [localhost]: Approve Collections (6 retries left).
FAILED - RETRYING: [localhost]: Approve Collections (5 retries left).
FAILED - RETRYING: [localhost]: Approve Collections (4 retries left).
FAILED - RETRYING: [localhost]: Approve Collections (3 retries left).
FAILED - RETRYING: [localhost]: Approve Collections (2 retries left).
FAILED - RETRYING: [localhost]: Approve Collections (1 retries left).
failed: [localhost] (item=/__xxxxxx) => {"__ah_collection_file": "/xxxx", "ansible_loop_var": "__ah_collection_file", "attempts": 10, "changed": false, "msg": "Unable to approve at collectionsxxxxxx: Awaiting approval not found"}


PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   


##[error]Bash exited with code '2'.
Finishing: Run publish playbook


This is something the error looks like.

**Comment by Tompage1994** [comment]
In that case, the issue isn't with the ah_approval module, it'll be with the module you use beforehand to get the collection into AH. If there is no awaiting approval then my guess is that ah_collection hasn't worked here? Either that or you have auto_approved the collection using ah_collection and the collection is actually usable in AH. Could you confirm if this is there? Also confirm if there are any obvious failures of tasks in task management for AH?

**Comment by djdanielsson** [comment]
can you show us the whole playbook?

**Comment by sean-m-sullivan** [comment]
@Tompage1994 From the looks of it, it looks like a wait/interval problem, we are not waiting long enough for the approval to be generated. We want to add a wait/interval to the approval function and the collections/approval module. like this
[wait function module](https://github.com/ansible/awx/blob/9f8b3948e1aad75620bec818f1965b1bb1acbf6e/awx_collection/plugins/modules/project_update.py#L128)
[wait function](https://github.com/ansible/awx/blob/9f8b3948e1aad75620bec818f1965b1bb1acbf6e/awx_collection/plugins/modules/project_update.py#L128)

**Comment by sean-m-sullivan** [comment]
This should be solved by the above PR #192 it was a problem with an endpoint change, and that fix should solve this.
