### ISSUE TITLE
Publish role is overwriting existing collection version

### ISSUE THREAD

**Issue by tonyreveal** [redhat-cop/ah_configuration#139]
AAP 2.2.  
PAH Server version: 4.5.0
Pulp Ansible Version: 0.13.0

Trying to publish new version of existing collection with the `ah_overwrite_existing` var set to `false`.  However it always deletes the existing version.  I did see the note `This will only work if the account being used has correct privileges`.  We've tried the admin account with password and also tried a token.  We've also tried other super-user accounts with the same results.

When you run the playbook it will delete the collection and will fail with an error but you can see `overwrite_existing` is set to `true` (below output).  Then run the playbook again and it will 

```json
{
  "invocation": {
    "module_args": {
      "namespace": "cscdev",
      "name": "collectiontest",
      "path": "/var/tmp/Collectiontest/cscdev-collectiontest-1.1.13.tar.gz",
      "auto_approve": false,
      "overwrite_existing": true,
      "ah_host": "pah-dev.cscglobal.com",
      "ah_username": "admin",
      "ah_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
      "wait": true,
      "state": "present",
      "ah_path_prefix": null,
      "validate_certs": null,
      "ah_token": null,
      "version": null
    }
```

When you run the playbook again it will publish the new version of the collection.

**Comment by djdanielsson** [comment]
where are you putting ah_overwrite_existing to false? can you print out the hostvars at the start of the playbook to see if you see it as true or false?

**Comment by tonyreveal** [comment]
They originally had it as a parameter in the collection defintion.  I changed it to pass it as a var to the role which solved the `overwrite_existing: true` issue.  However, now it doesn't do anything.  It keeps the existing version and does not publish another version (isn't keeping old versions).  The expectation is that they be able to click the Version drop down box and see many versions to choose from.

```yaml
- name: Import ah_configuration role
  import_role:
    name: redhat_cop.ah_configuration.publish
  vars:
    ah_overwrite_existing: false
```

**Comment by djdanielsson** [comment]
thanks for the update, I agree I would expect that result. We will have to try and do some deep debugging but that might take a while.

**Comment by Tompage1994** [comment]
What relevant vars are set for this role? Is a version set in the galaxy.yml? The version doesn't get bumped by this role, so if an existing collection exists of the matching version and you have told it not to overwrite existing it should do nothing in theory

**Comment by tonyreveal** [comment]
@Tompage1994 A version is set in galaxy.yml and increased each time they want to publish a new version.

Right now they have a test collection version 1.1.13.  I myself increased the version in galaxy.yml to 1.1.14 and again to 1.1.15.  The  job skips publishing the new version

```
TASK [redhat_cop.ah_configuration.publish : Publish Collections] ***************
ok: [localhost] => (item=/var/tmp/cscdev.collectiontest/cscdev-collectiontest-1.1.15.tar.gz)

TASK [redhat_cop.ah_configuration.publish : Publish Collection | Wait for finish the publish creation] ***
FAILED - RETRYING: [localhost]: Publish Collection | Wait for finish the publish creation (50 retries left).
ok: [localhost] => (item={'failed': 0, 'started': 1, 'finished': 0, 'ansible_job_id': '837873964978.136', 'results_file': '/tmp/.ansible_async/837873964978.136', 'changed': False, '__ah_collection_file': '/var/tmp/cscdev.collectiontest/cscdev-collectiontest-1.1.15.tar.gz', 'ansible_loop_var': '__ah_collection_file'})

TASK [redhat_cop.ah_configuration.publish : Approve Collections] ***************
skipping: [localhost] => (item=/var/tmp/cscdev.collectiontest/cscdev-collectiontest-1.1.15.tar.gz) 
```

**Comment by Tompage1994** [comment]
That shows skipping the approval, presumably because `ah_auto_approve` is `false`.

And to check, the collection hasn't been published to AH (including potentially sat in the approval queue)?

**Comment by tonyreveal** [comment]
@Tompage1994 I just checked their code, they've published v1.1.17.  It's the only version in Automation Hub.  And they now have auto approve set to true.

```
---
ah_collections:
  - collection_name: Omitted
    git_url: Omitted
    version: "{{ version }}"
    ah_auto_approve: true
...
````

```
TASK [redhat_cop.ah_configuration.publish : Publish Collections] ***************
ok: [localhost] => (item=/var/tmp/cscdev.collectiontest/cscdev-collectiontest-1.1.17.tar.gz)

TASK [redhat_cop.ah_configuration.publish : Publish Collection | Wait for finish the publish creation] ***
FAILED - RETRYING: [localhost]: Publish Collection | Wait for finish the publish creation (50 retries left).
FAILED - RETRYING: [localhost]: Publish Collection | Wait for finish the publish creation (49 retries left).
FAILED - RETRYING: [localhost]: Publish Collection | Wait for finish the publish creation (48 retries left).
changed: [localhost] => (item={'failed': 0, 'started': 1, 'finished': 0, 'ansible_job_id': '171683425514.136', 'results_file': '/tmp/.ansible_async/171683425514.136', 'changed': False, '__ah_collection_file': '/var/tmp/cscdev.collectiontest/cscdev-collectiontest-1.1.17.tar.gz', 'ansible_loop_var': '__ah_collection_file'})

TASK [redhat_cop.ah_configuration.publish : Approve Collections] ***************
skipping: [localhost] => (item=/var/tmp/cscdev.collectiontest/cscdev-collectiontest-1.1.17.tar.gz) 
```
![Capture](https://user-images.githubusercontent.com/22101936/183446243-2520fe79-89a4-4ef2-b45a-d471c6f9ed4f.PNG)

**Comment by Tompage1994** [comment]
So thats working now? Could it be that before they were just say in the approvals queue in the UI?

**Comment by tonyreveal** [comment]
@Tompage1994 It's not doing what's expected which is to have multiple versions in the drop down.  It always deletes existing versions.  If a user manually uploads a new version, that drop down will contain 2 or more versions.  The publish role in the collection is deleting what it finds before publishing the new version.

And no, they were not in the approvals queue.

**Comment by Tompage1994** [comment]
Ah, I've got you. Not sure why that would be happening at all. I can try looking into it

**Comment by djdanielsson** [comment]
closing
