### ISSUE TITLE
Role to increase the collection version automatically

### ISSUE THREAD

**Issue by sean-m-sullivan** [redhat-cop/ah_configuration#144]
This is just an idea that was thrown out. 
change the galaxy version in a lineinfile/blockinfile. So if it's the first build/publish, there's nothing to do, just make sure a valid line exists. From there on, if x.y.z, where x.y.z > the x.y.z from the data gather at the beginning, then build and publish.

if it isn't, then change x.y.z to x1,y1,z1 and build/publish

and have it be an option to turn on in the role. This is low priority, but something that I've thought of for a while and someone pointed out a way to maybe do it.

**Comment by sean-m-sullivan** [comment]
@dsglaser

**Comment by djdanielsson** [comment]
so an issue I have with this, what would happen if you run publish 2 times in a row without changing anything? I don't think there would be a way to know if there were changes and thus it would publish a new version with no changes. Also I think the better way to do it is require galaxy file to be template and pull from hub the current version and then +1 that version and assign that to the variable.

**Comment by sean-m-sullivan** [comment]
After rethinking that this is something to be fixed more at the ansible-galaxy build level, it might be an OPTION to add to the publish role, but its likely something not used by many, so closing this unless we get some demand for it.
