### ISSUE TITLE
can you generate a new release to ansible galaxy for the change made in last few days

### ISSUE THREAD

**Issue by gearboxscott** [redhat-cop/ah_configuration#150]
can someone release so PR#147 and PR#148 can be pulled into private automation hub via community repo sync. 

thank you

**Comment by djdanielsson** [comment]
we are working on a few fixes before we do another release

**Comment by djdanielsson** [comment]
we have 2 known issues that are not fixed... I am not sure if we want to do a release with those issues still around or not...
