### ISSUE TITLE
ah_collection minor bug

### ISSUE THREAD

**Issue by djdanielsson** [redhat-cop/ah_configuration#156]
every so often with ah_collection module when pushing a collection while having ah_overwrite_existing set to true it errors out. It has something to do with the time it takes to delete the current namespace I believe and if you re-run the publish role again it will complete as expected.

**Comment by sean-m-sullivan** [comment]
@djdanielsson I think we've made the timeout better, and fixed the issue with the approval, I haven't seen this again like I had in the past, close for now?

**Comment by djdanielsson** [comment]
Sure if you think it's fixed I am fine with closing this issue
