### ISSUE TITLE
ah_ee_registry_index failing for custom EE remote registries

### ISSUE THREAD

**Issue by rthdev** [redhat-cop/ah_configuration#167]
When configuring a custom EE remote registry (Quay for instance), the ee_registry_index task fails because indexing is only supported for registry.redhat.io

There should be a variable like "index: true|false" for ah_ee_registries and ah_registry_index should not try indexing when set to false.

**Comment by Tompage1994** [comment]
Sorry for not getting back to this quicker. I like the idea you've proposed here and it should be fairly easy to implement. Thanks for bringing it to attention.

We should only run the `ah_ee_registry_index` module in the `ee_registry_index` role if `__ee_registry_item.index` is true 

i.e.  add
```
when: "{{ __ee_registry_item.index | default(false) }}"
```

Whilst at it, it would be good to add the same functionality to the `ee_registry_sync` role.
