### ISSUE TITLE
Need a way to release to infra namespace changing doc_fragments

### ISSUE THREAD

**Issue by Tompage1994** [redhat-cop/ah_configuration#175]
# Summary
When we do a release we will need to change the following line

```
extends_documentation_fragment: redhat-cop.ah_configuration.auth
```
(or similar) in multiple places to be `infra.ah_configuration.*` instead.

We should also update any other references as well. We can't just change all this though as it would break the doc fragments for redhat_cop.

# Issue Type

- Bug Report

**Comment by sean-m-sullivan** [comment]
After relooking the only traces of redhat_cop remain in some of our testing and workflows, this should now be closed as Tom fixed 99.99% of it already!
