### ISSUE TITLE
Add new module for adding group roles to replace the group_perms module

### ISSUE THREAD

**Issue by Tompage1994** [redhat-cop/ah_configuration#179]
# Summary

Add new module for adding group roles to replace the group_perms module

The endpoint to do this is something like: /api/pulp/api/v3/groups/{id}/add_role/

# Issue Type

- Feature request

**Comment by djdanielsson** [comment]
ok I added discussions so now feature requests can be put there if we want instead of issues, Idk which I like better.

**Comment by Tompage1994** [comment]
> ok I added discussions so now feature requests can be put there if we want instead of issues, Idk which I like better.

Lets go with discussions for now. My only issue is whether they will be visible enough there. We can change if required

**Comment by sean-m-sullivan** [comment]
This is going to be on hold, as it is dependent on https://issues.redhat.com/browse/AAH-2080

Until that endpoint works, this will not and is impossible to work on.

**Comment by marszip** [comment]
Are there any updates to this issue, the Red Hat issue which was blocking seems to be resolved. Not sure if that is the case, but we would like to manage our roles with this collection.

**Comment by sean-m-sullivan** [comment]
its still and issue, but its in our backlog

**Comment by EamonTracey** [comment]
+1 on this issue. I would like to be able to test ah_group_perm (or a new role module) in the galaxy_ng CI workflows

**Comment by sean-m-sullivan** [comment]
Closing as this was fixed in #299
