### ISSUE TITLE
Update EE namespace for AH 4.6

### ISSUE THREAD

**Issue by Tompage1994** [redhat-cop/ah_configuration#183]
# Summary

The ee_namespace API has changed in 4.6 so the module is broken there. 

There is now a _ui API so this can be redesigned. I don't know whether there was in 4.5 or before. We really don't need to be using the pulp API for this because its a PITA.

`https://ah.aap23.local/api/galaxy/_ui/v1/execution-environments/namespaces/ee-29-rhel8/ `

# Issue Type

- Bug Report

**Comment by sean-m-sullivan** [comment]
It looks like in 4.6 The namespace API was discontinued to just be repositories. I'll be putting in a PR to note that in the module and role.

https://github.com/ansible/galaxy_ng/pull/1397

**Comment by sean-m-sullivan** [comment]
Closing this with the recent merge, if we want to revisit, we can reopen, but I don't think the API is changing back.
