### ISSUE TITLE
Ensure roles are called in the dispatch role

### ISSUE THREAD

**Issue by Tompage1994** [redhat-cop/ah_configuration#220]
# Summary
Not all roles are currently added to the default running order of the dispatch role. For example ee_namespace and ah_role should probably both be added (plus more).

This is an easy fix but lets track in this issue what we need to change.

# Issue Type

- Bug Report
- Question

CC @sean-m-sullivan @djdanielsson

**Comment by djdanielsson** [comment]
I don't have much to comment on this, as most know I am not a fan of the dispatch roles and never use them myself. I say if they are missing then they should be added for those who do use the role.

**Comment by jon4hz** [comment]
Is it intended that the dispatch role only creates ee_namespaces but not collection namespaces?

**Comment by sean-m-sullivan** [comment]
Double checked this, everything is included, and the collection namespace role/var is namespace/ah_namespaces and is in it.
