### ISSUE TITLE
repository_sync role should work in same way as ee_repository_sync role

### ISSUE THREAD

**Issue by Tompage1994** [redhat-cop/ah_configuration#244]
# Summary
Should do async against both repos so they work in parallel and also run when 'sync' option set.

# Issue Type

- Bug Report

**Comment by djdanielsson** [comment]
I removed async from these because there were issues

**Comment by djdanielsson** [comment]
it was in #124 and #126

**Comment by Tompage1994** [comment]
That makes sense. I think we want to keep the current structure, just we should kick them both off in fire and forget (`async: 0`) and then retrieve the results after, that way they can run concurrently. The issue now is that they will sequentially run and take a long time

**Comment by sean-m-sullivan** [comment]
Async was turned back on for these, closing
