### ISSUE TITLE
timeout needs to be added as an option

### ISSUE THREAD

**Issue by sean-m-sullivan** [redhat-cop/ah_configuration#274]
# Summary
Setting this as note, if a request takes more then 10 seconds it can timeout, due to default timeout value set in the ansible library. This is fixed by sending the option. Basically this PR logic needs to be added to the collection
https://github.com/ansible/awx/pull/14157

This is work that needs to be done, that anyone can do, but putting it here so we do not forget it needs to be done.

# Issue Type

- Bug Report

**Comment by Tompage1994** [comment]
I assume this isn't actually `blocked - upstream`. The reference to the awx collection was an example I believe.

**Comment by sean-m-sullivan** [comment]
I think we were waiting to make sure it passed QA over on AWX to make sure the solution was similar.
