### ISSUE TITLE
Please add support for remote repository for validated content

### ISSUE THREAD

**Issue by dbk-rabel** [redhat-cop/ah_configuration#295]
Hi.

At the moment you can only ah_repository_certified and ah_repository_community for infra.ah_configuration. But as of AAP2 2.4 there is a possibility to add a remote to the validated content repository as well to sync it.

Could you add some support for this, for example by adding a parameter ah_repository_validated ?

Yours
  David

**Comment by rochacbruno** [comment]
Looks like this is addressed by https://github.com/ansible/galaxy_collection/pull/294

**Comment by djdanielsson** [comment]
this has been added but has not been released yet

**Comment by sean-m-sullivan** [comment]
@dbk-rabel its up on galaxy now in the infra.ah_configuration release

**Comment by dbk-rabel** [comment]
Thank you very much!
