### ISSUE TITLE
Migrate to oci-env for CI workflows

### ISSUE THREAD

**Issue by rochacbruno** [redhat-cop/ah_configuration#336]
Currently this repo uses the legacy galaxy dev environment that will be soon removed (already unmaintained)

https://github.com/ansible/galaxy_collection/blob/devel/.github/workflows/ci_standalone_versioned.yml#L26 

## Proposal

Move to oci-env to spinup the galaxy server

Reference: https://github.com/ansible/galaxy_ng/blob/eb6bc8197c182f742233a743e3dd9fa962996413/.github/workflows/ci_oci-env-integration.yml#L35-L56

**Comment by sean-m-sullivan** [comment]
Was trying to figure this out and hit a wall
https://github.com/sean-m-sullivan/galaxy_collection/actions/runs/6799024714/job/18484385326

and code here
https://github.com/sean-m-sullivan/galaxy_collection/blob/devel/.github/workflows/ci_oci-env-integration.yml
