### ISSUE TITLE
Version 2.0.5 is not available from community repo (not published)

### ISSUE THREAD

**Issue by bogdanmuresan** [redhat-cop/ah_configuration#371]
# Summary

Version 2.0.5  infra.ah_configuration has not been published to community repo.

[ah_configuration](https://galaxy.ansible.com/ui/repo/published/infra/ah_configuration/)

Looks like release workflow failed:
https://github.com/ansible/galaxy_collection/actions/runs/8067095060

**Comment by Tompage1994** [comment]
Thanks for bringing this back to the front of my attention. I was meant to take a look at why the CI was failing. I think I've got a fix for this now and once merged I'll cut a new release (though it probably won't be version 2.0.5)

**Comment by Tompage1994** [comment]
@bogdanmuresan version 2.0.6 has now been published [here](https://galaxy.ansible.com/ui/repo/published/infra/ah_configuration/)
