### ISSUE TITLE
Can't limit architecture for EE image sync

### ISSUE THREAD

**Issue by myllynen** [redhat-cop/ah_configuration#379]
There is currently no way to limit which OS / architecture builds of EE images will be synced meaning that when syncing, e.g., ansible-automation-platform/ee-minimal-rhel9 with AAP 2.4 one gets the following:

linux / amd64
linux / arm64
linux / ppc64le
linux / s390x

In most cases when using amd64 only this means handling each image takes 4 times more bandwidth, time, and storage than what would really be needed. I'm not sure does the API allow this currently.

Thanks.

**Comment by sean-m-sullivan** [comment]
This would be a question for how to specify this in the Gui as well, not sure on the API, the collection itself just does what we tell it, The question is how to tell it which Architecture.

**Comment by myllynen** [comment]
I can't find any way to do that in the Web UI currently, we now have RFE for that, perhaps we can look at this issue again once the RFE is resolved, see https://issues.redhat.com/browse/AAP-22653. Thanks.

**Comment by Tompage1994** [comment]
This can be revisited once AAP-22653 has been resolved
