### ISSUE TITLE
Release a new version?

### ISSUE THREAD

**Issue by dkolepp** [redhat-cop/ah_configuration#42]
Looks like several new modules are included in recent commits.  Any way to release a new version of this collection?

**Comment by Tompage1994** [comment]
Hi @dkolepp,

I'll do a release now. I was going to wait until we had developed the wrapper roles which I should be able to get to today. But I understand it would be great to get these out and usable so doing so now!

**Comment by Tompage1994** [comment]
See v0.5.0 has been released https://galaxy.ansible.com/redhat_cop/ah_configuration

**Comment by dkolepp** [comment]
Thanks for releasing this!  I'm actively using these at the moment, and also digging into the code.  I suspect I'll be able to provide feedback/issues, as well as possibly add a few contributions.

Thanks again!
