### ISSUE TITLE
New release soon?

### ISSUE THREAD

**Issue by dbk-rabel** [redhat-cop/ah_configuration#434]
Hi.

I'm sorry. Not sure how to get in touch, so I try this way.

Will there be a new collection release soon?

We would love to be finally able to use the new parameters from https://github.com/ansible/galaxy_collection/pull/399 .

Yours
  David

**Comment by djdanielsson** [comment]
We are currently in the process of making some more changes and then likely to do another release, if you need what is currently in devel you can pull from the repo or clone the repo and build it

**Comment by dbk-rabel** [comment]
Thank you! We will wait for the release then, because we want to obtain the collection the "official" way via Ansible Galaxy.

**Comment by dbk-rabel** [comment]
@djdanielsson Can you roughly estimate when the release is coming? Is it going to be likely within the next few weeks?

**Comment by sean-m-sullivan** [comment]
We released the new changes 13 days ago
https://galaxy.ansible.com/ui/repo/published/infra/ah_configuration/docs/

With the async timeout feature

It just doesn't show up as a tag, due to some other issues going on, stay tuned for more updates as we are working on releasing infra.aap_configuration, and depreciating this repo.

**Comment by dbk-rabel** [comment]
Sorry, didn't see that. Thanks!

**Comment by dbk-rabel** [comment]
@sean-m-sullivan @djdanielsson  Would you mind adding a git tag 2.1.0 here?

**Comment by sean-m-sullivan** [comment]
@dbk-rabel what are we needing to add to that, we reworked everything to use on 2.5 over to the new infra aap configuration collection, just seeing what the ask is

**Comment by dbk-rabel** [comment]
@sean-m-sullivan There is a version 2.1.0 released but there is no tag "2.1.0" on any git commit as far as I can see. I think it was just forgotton, because all the earlier versions do have a git tag.

**Comment by dbk-rabel** [comment]
Hello and Happy New Year!

@sean-m-sullivan @djdanielsson I think my question is still open.

**Comment by sean-m-sullivan** [comment]
This is the 2.1.0 release, this repo was in a state of limbo where we had to rewrite it to be infra for release, but was supposed to be transitioning to an ansible release

https://github.com/ansible/galaxy_collection/tree/infra_release_2.1.0

**Comment by dbk-rabel** [comment]
Thank you!
