### ISSUE TITLE
ah_repository_sync replaces the AH API Token -> Tower Project update fails

### ISSUE THREAD

**Issue by sigbjornaib** [redhat-cop/ah_configuration#50]
When using redhat_cop.ah_configuration.ah_repository_sync to perform an AH repository sync, the API token in Automation Hub is changed, and any Project Update in Tower fails with the following error message:
```    "ERROR! Error when finding available api versions from server0 (https://automationhub.ourdomain.local/api/galaxy/content/rh-certified/) (HTTP Code: 403, Message: Forbidden)"```

Manually creating a new API Token in the AH webui and updating the Crednetials in Tower resolves the issue, until another sync using  redhat_cop.ah_configuration.ah_repository_sync is performed.

The task in the playbook used is the following:
```
      - name: Sync repos
        redhat_cop.ah_configuration.ah_repository_sync:
          name: "{{ item }}"
          wait: true
          timeout: 900
          ah_host:          "{{ ah_host }}"
          ah_username:      "{{ ah_username | default(omit) }}"
          ah_password:      "{{ ah_password | default(omit) }}"
          ah_path_prefix:   "{{ ah_path_prefix | default(omit) }}"
          validate_certs:   "{{ ah_validate_certs | default(omit) }}"
        register: ah_repository_sync_result
        no_log: "{{ ah_repository_sync_secure_logging }}"
        loop:
          - community
          - rh-certified
```

**Comment by Tompage1994** [comment]
Unfortunately that is a limitation of the automation hub and something which there is not a great way around since only one token can be created and these modules use the tokens underneath. You do have a few different options here though:

1. Create a separate user which will have a _static_ token and use that for your project pulls and use a different user for these ah modules.
2. Instead of using `ah_password` and `ah_username` for this module, make use of the `ah_token` option instead and specify the same token you use in Tower to access collections.

**Comment by sigbjornaib** [comment]
Thank you for your feedback. redhat_cop.ah_configuration.ah_repository_sync works when using option 2. I do not see any options in the AH webui for adding static tokens to users.

I do wonder why clicking the "Sync" button manually in the webui works as expected while logged on as the "admin" account (no change to the API token), however using redhat_cop.ah_configuration.ah_repository_sync with the same "admin" account does change the API token.

If the reported bug is a limitation of the AH, why does pressing the Sync button not rotate the API keys in the same manner as the Ansible module?

**Comment by Tompage1994** [comment]
Apologies, what I meant by a _static_ token was that the user will not be logged into and have its token changed, nor will it be addressed by its username/password by any of the modules. The token itself is obtained in the same was as any other, just you can consider it to be 'static' by the fact it should never be changed. Its not a great process and I assume at some point there will be a better way in a future release.

I believe what happens in the UI is that a CSRF token is used to authenticate (I'm not 100% sure on that, or how it works though). All I know is if you use the modules with the username and password it will first gather a new token (therefore the old one will be defunct) and then use that to authenticate. You can instead just use a token and not use username and password.

**Comment by sigbjornaib** [comment]
Thank you. Using token to authenticate solves the issue for me.
