### ISSUE TITLE
Add support for disconnected environments

### ISSUE THREAD

**Issue by dmc5179** [redhat-cop/ah_configuration#57]
This collection works really well to sync content from AH to PAH. Most of my customers operate in fully disconnected environments. Using the same collection to both pull content down from AH and then push that content to the customer's PAH in their environment would make disconnected operations much easier.

**Comment by Tompage1994** [comment]
Hey, sorry for taking so long to get around to this.

I've had a go at understanding what you mean and have raised a PR which should help achieve this. From my understanding, just being able to pass in a URL for a remote collection to `ah_collection_upload` would work well for you here?

Likewise, you can use the `publish` role to do the same:

```
vars:
  ah_collection_list:
    - https://<collectionURL>.tar.gz
    - https://<collectionURL>.tar.gz

roles:
  - redhat_cop.ah_configuration.publish
```
Let me know if this isn't what you thought of
Thanks

**Comment by Tompage1994** [comment]
@dmc5179 please reopen this ticket if the fix won't be sufficient

**Comment by dmc5179** [comment]
@Tompage1994 This is great, thank you. I'll give your changes a try with our PAH in a fully air-gapped environment and go from there.
