### ISSUE TITLE
Missing modules to manage EE Remote Registries [PAH v4.4.1]

### ISSUE THREAD

**Issue by JoelKle** [redhat-cop/ah_configuration#67]
We run Private Automation Hub version:
Server version 4.4.1
Pulp Ansible Version 0.10.1

I couldn't find a module or role to manage Execution Environments > Remote Registries
Modules to create/edit remote registries, to "Sync from registry" and to "Index Execution Environments" would be great.

![grafik](https://user-images.githubusercontent.com/34544090/159925195-4b17f17c-46ad-42a7-a9a8-8beb5ee81fb1.png)

Thanks Joel

**Comment by Tompage1994** [comment]
There are a whole bunch of tasks we probably need to create here. I'll create an issue for each as they're all going to be separate features.

- [x] ah_ee_registry
- [x] ah_ee_registry_sync
- [x] ah_ee_registry_index

We also need to create

- [x] ah_ee_repository_sync

and update to be able to create:

- [x] ah_ee_repository


As a start I have just created `ah_ee_registry`

**Comment by sean-m-sullivan** [comment]
We should also create roles around there

- [ ] redhat_cop.ah_configuration.ee_registries 
- [ ] redhat_cop.ah_configuration.ee_registries_sync
- [ ] redhat_cop.ah_configuration.ee_registries_index

The variable to use for these should be:
ah_ee_registries

We really should have them around all modules, but Tom's stepped up with the modules, Just want to add to the do list, crossing fingers on myself getting spare time.

**Comment by Tompage1994** [comment]
I think we have everything on this now so closing.
