### ISSUE TITLE
Update group perms module

### ISSUE THREAD

**Issue by sean-m-sullivan** [redhat-cop/ah_configuration#78]
Latest galaxy renames object_permissions to object_roles

https://github.com/ansible/galaxy_ng/pull/1057

its an we need to either support either, or figure out how to support the change.

**Comment by djdanielsson** [comment]
@sean-m-sullivan is this still an issue?

**Comment by sean-m-sullivan** [comment]
I think this is next release coming out, so its something to still keep track of.

**Comment by sean-m-sullivan** [comment]
I've started work on this, and have most of the solution, the key is getting in proper tests and unbreaking things I broke to make it work.

**Comment by sean-m-sullivan** [comment]
Closing in favor of #179
