### ISSUE TITLE
This collection doesn't work with Keycloak users

### ISSUE THREAD

**Issue by Tompage1994** [redhat-cop/ah_configuration#94]
If using RHSSO to authenticate for AH, this collection does not seem to work (would be good to get someone to verify its not just something wrong with my setup).

I suppose this probably makes sense as it required you to go off to an external site. Its also not possible to log into a user from SSO in the API browser so that probably backs this up. 

We will definitely need to come up with a workaround for this, or at very least give explanation that only local users are supported.

EXTRA: the modules which allow `ah_token` do work with keycloak users only if you pass in `ah_token`

**Comment by Tompage1994** [comment]
cc @sean-m-sullivan

**Comment by sean-m-sullivan** [comment]
Oh Fun

**Comment by Tompage1994** [comment]
It was always going to happen given the nature of the way the API is put together...

**Comment by Tompage1994** [comment]
It looks like the _ui will go soon which would mean its a bit simpler and we can just use one form of auth and can hopefully create a flow to deal with SSO users 

https://issues.redhat.com/browse/AAH-770

**Comment by sean-m-sullivan** [comment]
Oh I agree, thats why I was hesitant on the 1.0.0, basically once this is finished and we have working everything under the new API, its likely the 1.0.0 point

**Comment by Tompage1994** [comment]
Fair enough, I hadn't had the chance to go searching through to see what changes are upcoming and it looks like there may be a fair amount under the covers

**Comment by sean-m-sullivan** [comment]
It's been so long I don't think I realized it was a complete overhaul and removal, expected some time for overlap

**Comment by djdanielsson** [comment]
what is the current state with 2.2?

**Comment by sean-m-sullivan** [comment]
unchanged, we still have the issue, you can create a controller service account though as a workaround for now.
