### ISSUE TITLE
ah_repository expected behavior?

### ISSUE THREAD

**Issue by t-readyroc** [redhat-cop/ah_configuration#98]
Automation Hub 4.2.3

I'm writing a Tower job to sync our local AH. I currently have the following playbook:

~~~yaml
    - name: Configure the repos
      redhat_cop.ah_configuration.ah_repository:
        ah_host: "{{ aahBase }}"
        ah_username: admin
        ah_password: "{{ aahAdminPass }}"
        validate_certs: false
        name: "{{ item.aahRepoName }}"
        url: "{{ item.aahRepoURL }}"
        requirements_file: "{{ item.aahReqFile }}"
        auth_url: "{{ item.aahRepoAuthURL | default(omit) }}"
        token: "{{ item.aahRepoToken | default(omit) }}"
        proxy_url: "{{ proxy_env.http_proxy }}"
      loop: "{{ aahRepos }}"

    - name: Sync the repos
      redhat_cop.ah_configuration.ah_repository_sync:
        ah_host: "{{ aahBase }}"
        ah_username: admin
        ah_password: "{{ aahAdminPass }}"
        validate_certs: false
        name: "{{ item.aahRepoName }}"
        wait: true
      loop: "{{ aahRepos }}"
~~~

But I noticed that every time I ran the playbook, the existing API token was negated. Is this expected behavior?

Testing was as follows.

Run with known token:

~~~
ansible-galaxy collection install -c -s https://automation-hub.exmple.com/api/galaxy/content/rh-certified --token <token> ansible.tower
Starting galaxy collection install process
Process install dependency map
Starting collection install process
Skipping 'ansible.tower' as it is already installed
~~~

Run the above playbook to add a new collection (updated requirements.yml), then attempt to run galaxy again (using the same token):

~~~
ansible-galaxy collection install -c -s https://automation-hub.example.com/api/galaxy/content/rh-certified --token <token> ansible.tower
Starting galaxy collection install process
Process install dependency map
ERROR! Error when finding available api versions from cmd_arg (https://automation-hub.example.com/api/galaxy/content/rh-certified) (HTTP Code: 403, Message: Forbidden)
~~~

**Comment by djdanielsson** [comment]
Yes I found this is the case, I am not positive if it is supposed/has to be like this so I will leave the case open and let others chime in but I would currently say yes it is expected behavior.

**Comment by djdanielsson** [comment]
One way around this would be to create a user and generate a token from that account and use that to pull your collections from as long as you never do anything with the API as that user and do everything API wise as the admin account.

**Comment by Tompage1994** [comment]
Yes, the way the login works (and kind of has to work unfortunately at the moment) is that a new token is created and each user can only have one token at a time. My suggestion is as @djdanielsson said, to create a user which you essentially only use for pulling from Tower and you never use that for use with the modules. That way you'll never recycle that token without meaning to. 

I wonder whether we could add something to our documentation to make this clearer?

**Comment by t-readyroc** [comment]
> Yes, the way the login works (and kind of has to work unfortunately at the moment) is that a new token is created and each user can only have one token at a time.

Sorry, trying to follow here. So, a new token is created any time a user logs in (using any of the modules)?

> My suggestion is as @djdanielsson said, to create a user which you essentially only use for pulling from Tower and you never use that for use with the modules. That way you'll never recycle that token without meaning to.

I guess I wasn't aware that individual users could have their own API tokens? I've only been dealing with the single token generated from `/ui/token` to this point, & it definitely gives the warning that, "loading a new token will delete your old token."

**Comment by djdanielsson** [comment]
yes because it is basically an auth token for that user account so if that is being used for API calls or just pulling down collections it is the same token, so if you were to call the token API/module again it generates a new one that deletes the old one you were using for collections. That is why I suggested creating a user that you won't do API calls with to just pull down collections and use that token to have a constant token to use for collections.

**Comment by t-readyroc** [comment]
>  if you were to call the token API/module again it generates a new one that deletes the old one you were using for collections. 

That makes sense to me (calling the token module creates a new one for the acct). What I want to make sure of is that using login for _any_ of the other modules does the same thing?

I was just able to create and use a token under a test account to install a collection from my local hub, _and  then_ was able to go back & use the token from the Admin user acct as well, so I now understand that individual accounts can have their own tokens (I couldn't find this info anywhere in documentation, and it's certainly not clear from the UI). So, your workaround of having an acct just for Tower to connect & pull from the local hub using its token makes sense.

Thanks for taking the time to clarify all of this, btw.
