### ISSUE TITLE
2 different no_log variables for new ee roles 

### ISSUE THREAD

**Issue by rthdev** [redhat-cop/ah_configuration#99]
New ee roles (ee-registry-sync, ee-registry-index ee-repository-sync) use 2 variables for values of no_log parameter. (task 1 and task 2 use a separate variable for no_log value)

One of them seems unintialized. 

Example for  ah_configuration/roles/ee_repository_sync/tasks/main.yml :
task 1 uses  no_log: "{{ ah_configuration_ee_repository_secure_logging }}"
task 2 uses no_log: "{{ ah_configuration_ee_repository_**sync**_secure_logging }}"

defaults only specifies ah_configuration_ee_repository_secure_logging

I'd expect to either only use the defined variable from roles defaults or initialize the second variable from same source

**Comment by djdanielsson** [comment]
thank you for letting us know, I am thinking we will just change task 2 to match task 1 but I will let the other maintainers chime in to see if they have a reason to keep them different.

**Comment by Tompage1994** [comment]
Yes, this looks like something I may have done by accident when adding the async stuff previously.

The readmes refer to it without the `_sync_` and that'll be the way it has previously worked so I say go with that. I've identified three places where this issue exists and I will raise a PR now to fix them.
